### PR TITLE
Setup the .github folder

### PR DESCRIPTION
**Pull request by oblm**
#### Description
* Setup the `.github` directory as per [setting-guidelines-for-repository-contributors/](https://help.github.com/articles/setting-guidelines-for-repository-contributors/).
* Update links in docs so that moving `CONTRIBUTING.md` does not break them.
#### Tests
None
#### Documentation
This is documentation.
#### Primary reviewers
@ElleEss

### CODE REVIEW

**Comment by samiwh** [comment]
@oblm this has been up for a few days now. Is anything blocking it being merged other than re-running CI?

**Comment by zeroZshadow** [comment]
Is the linting for this failing, as the links it's checking for will only be valid AFTER this has been merged?

**Comment by oblm** [comment]
Merging is blocked due to an error in the linter. https://github.com/spatialos/UnityGDK/pull/30, which fixes the linter, will unblock me when merged.

**Comment by firtina-improbable** [comment]
Do you still need to change these links to relative:

```md
[contributions](https://github.com/spatialos/UnityGDK/blob/master/.github/CONTRIBUTING.md) policy. However, we are accepting issues and we do want your [feedback](https://github.com/spatialos/UnityGDK/blob/master/README.md#give-us-feedback).
```

**Comment by oblm** [comment]
@firtina-improbable https://github.com/spatialos/UnityGDK/pull/30 changes these link paths to relative ones, as @jamiebrynes7 also inherited the problem on his branch.

**Comment by firtina-improbable** [comment]
Ah I see, OK

**Comment by jamiebrynes7** [comment]
@oblm Should be unblocked by the linting changes :)

**Pull request merged**
