### PR TITLE
moving prefab preprocessor from playground to GameObjectRepresentation

### PR DESCRIPTION
**Pull request by jessicafalk**
**Contributions**: We are not currently taking public contributions - see our [contributions](CONTRIBUTING.md) policy. However, we are accepting issues and we do want your [feedback](../README.md#give-us-feedback).

-------

#### Description
Because if you create your new project and you don't have it, it will completely break.

#### Tests
tested in my own small test project

#### Documentation
none

#### Primary reviewers
@zeroZshadow

### CODE REVIEW

**Comment by jessicafalk** [comment]
sorry about that, should be fixed now

**Comment by zeroZshadow** [comment]
The namespace isn't fixed now

**Comment by firtina-improbable** [comment]
LGTM for MVP, ideal solution is moving it into a module that adds on top of monobehaviour support.

**Comment by jessicafalk** [comment]
@firtina-improbable  agree with that. definitely needs to be moved with the rest of the monobehaviour stuff!

I think I fixed everything now, please take another look @zeroZshadow

**Pull request merged**
