### PR TITLE
Move the Configuring your project section higher.

### PR DESCRIPTION
**Pull request by martinzlocha**
**Contributions**: We are not currently taking public contributions - see our [contributions](CONTRIBUTING.md) policy. However, we are accepting issues and we do want your [feedback](../README.md#give-us-feedback).

-------

#### Description
Slightly reordered doc order after discussion with @ElleEss.
#### Tests
How did you test these changes prior to submitting this pull request?
What automated tests are included in this PR?
#### Documentation
How is this documented (for example: release note, upgrade guide, feature page, in-code documentation)?
#### Primary reviewers
If your change will take a long time to review, you can name at most two primary reviewers who are ultimately responsible for reviewing this request. @ mention them.

### CODE REVIEW

**Comment by MPeti01** [comment]
I'm pretty sure it was like that but then @callumlawson moved it down? It also kind of makes sense to have it low because it's advanced project setup stuff and the signposting directs you to it only after looking at the stuff above. I don't have a strong opinion though, feel free to merge if it's been well discussed

**Comment by martinzlocha** [comment]
@MPeti01 Personally I think that the "Starting workers" part is very essential and you will have to look at that section before writing any code.

**Comment by jamiebrynes7** [comment]
It depends what we expect consumers of these docs will more immediately want for M2.

Its likely `Starting workers` is very important, `Setting up a new project` less so

**Comment by MPeti01** [comment]
@martinzlocha Tbh I'd kind of agree *if* that workers doc had more information about where you might want to edit the WorkerConnectors, ie AddWorkerSystems(), which it really should. What's in there right now is not that useful for someone starting out imo

**Comment by jessicafalk** [comment]
it is important as you need to know how to actually add workers to the scene

however, I'm also in the process of adding more information about the connection flow

**Pull request merged**
